### ISSUE TITLE
Storage losing contents when world loads

### ISSUE THREAD

**Issue by titanium-cid** [AtomicBlom/HomecraftMineware#11]
Hi

I am having an issue with the storage (drawers and barrels) losing their contents when the world loads. I double checked and test this and I get this message in the logs:

`[19:01:50] [Server thread/ERROR]: Failed to load data for block entity tile.hcmw:bed_side_drawers
java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(Unknown Source) ~[?:1.8.0_111]
	at com.github.atomicblom.hcmw.shaded.compatlayer.tools.ItemStackList.remove(ItemStackList.java:47) ~[ItemStackList.class:?]
	at com.github.atomicblom.hcmw.shaded.compatlayer.tools.ItemStackList.remove(ItemStackList.java:10) ~[ItemStackList.class:?]
	at java.util.AbstractList$Itr.remove(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.removeRange(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.clear(Unknown Source) ~[?:1.8.0_111]
	at com.github.atomicblom.hcmw.block.tileentity.BaseSimpleInventoryTileEntity.func_145839_a(BaseSimpleInventoryTileEntity.java:290) ~[BaseSimpleInventoryTileEntity.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) [lr.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [aid.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1131) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1064) [ls.class:?]
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:368) [mp.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:163) [mp.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[19:01:50] [Server thread/ERROR]: A TileEntity tile.hcmw:bed_side_drawers(com.github.atomicblom.hcmw.block.tileentity.BedSideDrawersTileEntity) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(Unknown Source) ~[?:1.8.0_111]
	at com.github.atomicblom.hcmw.shaded.compatlayer.tools.ItemStackList.remove(ItemStackList.java:47) ~[ItemStackList.class:?]
	at com.github.atomicblom.hcmw.shaded.compatlayer.tools.ItemStackList.remove(ItemStackList.java:10) ~[ItemStackList.class:?]
	at java.util.AbstractList$Itr.remove(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.removeRange(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.clear(Unknown Source) ~[?:1.8.0_111]
	at com.github.atomicblom.hcmw.block.tileentity.BaseSimpleInventoryTileEntity.func_145839_a(BaseSimpleInventoryTileEntity.java:290) ~[BaseSimpleInventoryTileEntity.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) [lr.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [aid.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1131) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1064) [ls.class:?]
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:368) [mp.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:163) [mp.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[19:01:50] [Server thread/ERROR]: Failed to load data for block entity tile.hcmw:item_barrel
java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(Unknown Source) ~[?:1.8.0_111]
	at com.github.atomicblom.hcmw.shaded.compatlayer.tools.ItemStackList.remove(ItemStackList.java:47) ~[ItemStackList.class:?]
	at com.github.atomicblom.hcmw.shaded.compatlayer.tools.ItemStackList.remove(ItemStackList.java:10) ~[ItemStackList.class:?]
	at java.util.AbstractList$Itr.remove(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.removeRange(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.clear(Unknown Source) ~[?:1.8.0_111]
	at com.github.atomicblom.hcmw.block.tileentity.BaseSimpleInventoryTileEntity.func_145839_a(BaseSimpleInventoryTileEntity.java:290) ~[BaseSimpleInventoryTileEntity.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) [lr.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [aid.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1131) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1064) [ls.class:?]
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:368) [mp.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:163) [mp.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[19:01:50] [Server thread/ERROR]: A TileEntity tile.hcmw:item_barrel(com.github.atomicblom.hcmw.block.tileentity.ItemBarrelTileEntity) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(Unknown Source) ~[?:1.8.0_111]
	at com.github.atomicblom.hcmw.shaded.compatlayer.tools.ItemStackList.remove(ItemStackList.java:47) ~[ItemStackList.class:?]
	at com.github.atomicblom.hcmw.shaded.compatlayer.tools.ItemStackList.remove(ItemStackList.java:10) ~[ItemStackList.class:?]
	at java.util.AbstractList$Itr.remove(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.removeRange(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.clear(Unknown Source) ~[?:1.8.0_111]
	at com.github.atomicblom.hcmw.block.tileentity.BaseSimpleInventoryTileEntity.func_145839_a(BaseSimpleInventoryTileEntity.java:290) ~[BaseSimpleInventoryTileEntity.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) [lr.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [aid.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1131) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1064) [ls.class:?]
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:368) [mp.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:163) [mp.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[19:01:50] [Client thread/INFO]: Not hooking weather renderer for dimension [Overworld]`

This is part of a modpack called Harvest Mine on the curse launcher if you wanted to know what other mods are in the pack.

Hope that helps, and if I can get more info let me know.

Ta

Cid

**Comment by AtomicBlom** [comment]
Woah, that's not good! I'll try to get that fixed tonight!

**Comment by AtomicBlom** [comment]
Really sorry for how long this took. This has been fixed in 0.3.0.1
